---
title:      "electrs"
date:       2024-12-18T16:10:12-04:00
tags:       ["bitcoin"]
identifier: "20241218T161012"
---

Electrum Server in Rust

The server indexes the entire Bitcoin blockchain, 
and the resulting index enables fast queries for any given user wallet,

# configuration

Pruning must be turned off for electrs to work. 

txindex is allowed but unnecessary for electrs.

The highly recommended way of authenticating electrs is using cookie file.

Set rpccookiefile option of bitcoind to a file within an existing directory which it can access. 

electrs will wait for bitcoind to sync, however, you will be unable to use it until the syncing is done.

Example command for running bitcoind
``` shell
$ bitcoind -server=1 -txindex=0 -prune=0
```

We recommend running electrs --help to get an up-to-date list of options.

Electrs can be configured using command line, environment variables and configuration files

Important: you must configure db_dir to be either an empty directory or previously used by electrs! 


example config

``` toml
# DO NOT EDIT THIS FILE DIRECTLY - COPY IT FIRST!
# If you edit this, you will cry a lot during update and will not want to live anymore!

# This is an EXAMPLE of how configuration file should look like.
# Do NOT blindly copy this and expect it to work for you!
# If you don't know what you're doing consider using automated setup or ask an experienced friend.

# This example contains only the most important settings.
# See docs or electrs man page for advanced settings.

# File where bitcoind stores the cookie, usually file .cookie in its datadir
cookie_file = "/var/run/bitcoin-mainnet/cookie"

# The listening RPC address of bitcoind, port is usually 8332
daemon_rpc_addr = "127.0.0.1:8332"

# The listening P2P address of bitcoind, port is usually 8333
daemon_p2p_addr = "127.0.0.1:8333"

# Directory where the index should be stored. It should have at least 70GB of free space.
db_dir = "/some/fast/storage/with/big/size"

# bitcoin means mainnet. Don't set to anything else unless you're a developer.
network = "bitcoin"

# The address on which electrs should listen. Warning: 0.0.0.0 is probably a bad idea!
# Tunneling is the recommended way to access electrs remotely.
electrum_rpc_addr = "127.0.0.1:50001"

# How much information about internal workings should electrs print. Increase before reporting a bug.
log_filters = "INFO"
```

Environment variables override options in config files and finally arguments override everything else.

There are two special arguments --conf which reads the specified file and --conf-dir, which read all the files in the specified directory.

For each command line argument an environment variable of the same name with ELECTRS_ prefix, upper case letters and underscores instead of hyphens exists (e.g. you can use ELECTRS_ELECTRUM_RPC_ADDR instead of --electrum-rpc-addr).

Similarly, for each such argument an option in config file exists with underscores instead of hyphens (e.g. electrum_rpc_addr).

You need to use true value in case of flags (e.g. timestamp = true).

To connect to your Electrs server, you will need to point Electrum to your server using the ip_address:port syntax.

You will notice that most default servers in Electrum use the 50002 port (which is for SSL connections), while Electrs serves port 50001 and does not provide SSL out of the box.

You would need to either use a webserver to provide SSL (see SSL connection below), or connect without SSL.

. To tell Electrum to connect to your server without SSL, you need to add :t after the port (ie: localhost:50001:t).


Electrs will listen by default on 127.0.0.1:50001, which means it will only serve clients in the local machine.

This is configured via the electrum_rpc_addr setting

In order to use a secure connection, you can also use NGINX as an SSL endpoint by placing the following block in nginx.conf

``` nginx
stream {
        upstream electrs {
                server 127.0.0.1:50001;
        }

        server {
                listen 50002 ssl;
                proxy_pass electrs;

                ssl_certificate /path/to/example.crt;
                ssl_certificate_key /path/to/example.key;
                ssl_session_cache shared:SSL:1m;
                ssl_session_timeout 4h;
                ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
                ssl_prefer_server_ciphers on;
        }
}
```

start electrs
`electrs --log-filters INFO`

download the electrum client

RPC examples

You can invoke any supported RPC using netcat, for example:

``` shell
$ echo '{"jsonrpc": "2.0", "method": "server.version", "params": ["", "1.4"], "id": 0}' | netcat 127.0.0.1 50001
{"id":0,"jsonrpc":"2.0","result":["electrs 0.9.0","1.4"]}
```
